### ISSUE TITLE
error LNK2019: unresolved external symbol random referenced in function asn_random_between

### ISSUE THREAD

**Issue by fei4xu** [vlm/asn1c#339]
Hi, 

I compiled asn1 and used it successfully to compile my asn files to c in Ubuntu, then I copied the code to Windows (VS2015) to compile. 

I have this error now:
>error LNK2019: unresolved external symbol random referenced in function asn_random_between

It seems that `random()` is not a function in Windows but `rand()`.

I'm not usre if this can be fixed in a cross-platform way.

**Comment by fei4xu** [comment]
I did a quick test, `rand()` can also work in my Ubuntu 16.04 with GCC 7.4.0
