### ISSUE TITLE
INTEGER_constraint is undefined

### ISSUE THREAD

**Issue by pzb** [vlm/asn1c#182]
In building code with asn1c from current git, I'm getting the following error:

```gcc -I. -I/usr/include/ruby/2.3 -I/usr/include/ruby/2.3/ruby/backward -I/usr/include/ruby/2.3 -I.   -fPIC -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -mtune=generic -fPIC -m64 -o Trinomial.o -c Trinomial.c
Trinomial.c:23:2: error: ‘INTEGER_constraint’ undeclared here (not in a function)
  INTEGER_constraint,
  ^
make: *** [Trinomial.o] Error 1
```

Looking at `integer.h`, there is no constraint function defined.  This worked on previous releases of asn1c, so it must be some recent change that is generating this code.  I note that #180 also found issues with INTEGER_* functions, so I wonder if the older version didn't use type-specific functions and now does.

**Comment by pzb** [comment]
Git bisect shows that 1fa31c9e3e4182251439e8d5795fe4abf73f3152 was the commit that introduced this issue.  INTEGER.h was not updated to define a constraint function.

**Comment by brchiu** [comment]
hi @pzb, 

Thank you for digging out this problem and sorry for any problem incurred by my pull request.
I have submitted a fix #184, if you have time, could you kindly also have a trial using it ?

**Comment by vlm** [comment]
Merged @brchiu's solution.
