### ISSUE TITLE
make check in skeletons fails to build on WSL 22.4

### ISSUE THREAD

**Issue by swordXwind** [vlm/asn1c#496]
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

**make check** fails in the skeletons dir on the master branch.

`  CC       libasn1cskeletons_la-NativeInteger.lo
  CC       libasn1cskeletons_la-NativeInteger_oer.lo
  CC       libasn1cskeletons_la-NativeReal.lo
**NativeReal.c:642: error: initializer element is not constant**
Makefile:1395: recipe for target 'libasn1cskeletons_la-NativeReal.lo' failed
make[2]: *** [libasn1cskeletons_la-NativeReal.lo] Error 1
make[2]: Leaving directory '/home/eaf4weiziqing/Documents/asn1c-master/skeletons'`
