### PR TITLE
SEQUENCE OF SEQUENCE FIX.

### PR DESCRIPTION
**Pull request by enesunal**

### CODE REVIEW

**Comment by velichkov** [comment]
Hi @enesunal,

Thanks for the contribution. 
Can you provide some description or at least an ASN.1 definition that demonstrate the problem?

**Comment by enesunal** [comment]
I compiled my ASN.1 file [1] with `asn1c test.asn` and include my type's header in my project source[2].

When I try to compile with gcc-5.3, there are just a couple of warnings. When it comes to g++-5.3, it just stops with error. (No compile flags were being used)

[1] LTE RRC ASN.1 definition is:

```
TEST DEFINITIONS ::=
BEGIN
Test ::= SEQUENCE {
    field1 SEQUENCE OF SEQUENCE {
        field2 INTEGER,
        ...
    }
}
END
```

[2] My main.cpp file:

```
#include "Test.h"
#include "der_encoder.h"

int main() {
    return 0;
}
```

**Comment by mouse07410** [comment]
I think I can confirm the problem. It occurs consistently, but only with C++ compilers (g++ and clang++, tried with GCC-6.2 and clang-3.9.1).
```
g++ -maes -mpclmul -mrdrnd -msse2 -mssse3 -msse4.2 -mtune=native -Os -Ofast -I. -DPDU=Test -o Test.o -c Test.c
In file included from ./asn_SEQUENCE_OF.h:8:0,
                 from Test.h:14,
                 from Test.c:7:
Test.h:27:24: error: redefinition of 'struct Test::field1::<anonymous struct>::Member'
   A_SEQUENCE_OF(struct Member {
                        ^
./asn_SET_OF.h:17:16: note: in definition of macro 'A_SET_OF'
   void (*free)(type *);   \
                ^~~~
Test.h:27:3: note: in expansion of macro 'A_SEQUENCE_OF'
   A_SEQUENCE_OF(struct Member {
   ^~~~~~~~~~~~~
Test.h:27:24: error: previous definition of 'struct Test::field1::<anonymous struct>::Member'
   A_SEQUENCE_OF(struct Member {
                        ^
./asn_SET_OF.h:14:3: note: in definition of macro 'A_SET_OF'
   type **array;    \
   ^~~~
Test.h:27:3: note: in expansion of macro 'A_SEQUENCE_OF'
   A_SEQUENCE_OF(struct Member {
   ^~~~~~~~~~~~~
In file included from ./asn_system.h:26:0,
                 from ./asn_application.h:11,
                 from Test.h:11,
                 from Test.c:7:
Test.c:36:20: error: invalid use of incomplete type 'struct Member'
  { ATF_NOFLAGS, 0, offsetof(struct Member, field2),
                    ^
Test.c:36:36: note: forward declaration of 'struct Member'
  { ATF_NOFLAGS, 0, offsetof(struct Member, field2),
                                    ^
Test.c:45:20: error: invalid use of incomplete type 'struct Member'
  { ATF_NOFLAGS, 0, offsetof(struct Member, field3),
                    ^
Test.c:36:36: note: forward declaration of 'struct Member'
  { ATF_NOFLAGS, 0, offsetof(struct Member, field2),
                                    ^
Test.c:63:22: error: invalid application of 'sizeof' to incomplete type 'Member'
  sizeof(struct Member),
                      ^
In file included from ./asn_system.h:26:0,
                 from ./asn_application.h:11,
                 from Test.h:11,
                 from Test.c:7:
Test.c:64:2: error: invalid use of incomplete type 'struct Member'
  offsetof(struct Member, _asn_ctx),
  ^
Test.c:36:36: note: forward declaration of 'struct Member'
  { ATF_NOFLAGS, 0, offsetof(struct Member, field2),
                                    ^
Test.c:112:22: error: invalid application of 'sizeof' to incomplete type 'field1'
  sizeof(struct field1),
                      ^
In file included from ./asn_system.h:26:0,
                 from ./asn_application.h:11,
                 from Test.h:11,
                 from Test.c:7:
Test.c:113:2: error: invalid use of incomplete type 'struct field1'
  offsetof(struct field1, _asn_ctx),
  ^
Test.c:112:16: note: forward declaration of 'struct field1'
  sizeof(struct field1),
                ^~~~~~
make: *** [Test.o] Error 1
```

I've applied this fix to [my fork](https://github.com/mouse07410/asn1c.git).

Of course it is unclear whether it was intended to compile C code with C++ compilers, but why not...

**Comment by enesunal** [comment]
Any progress on this request? We want to use it on production but cannot make sure if it's the right way to do this or not.

**Comment by mouse07410** [comment]
> Any progress on this request? 

As I said, since your fix appears reasonably harmless, I've applied it to my fork of asn1c. It passes all the tests. If you mean "when (or if) @vlm would merge your PR", then I cannot answer - but you see there's a whole bunch of proposed fixes and enhancements that marinate in the queue for a few months already, with no observable movement.
 
> We want to use it on production but cannot make sure if it's the right way to do this or not.

IMHO the best way is to compile C code by a C compiler (as I said above). But your fix should be OK.

You might want to give my fork a try, what do you have to lose... It incorporates several of the useful enhancements and fixes proposed here.

**Comment by vlm** [comment]
Fixed in a different way, thank you for bringing this up!

Note: you have to use at least C++11 with its `decltype()` support.
